[project]
name = "backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
<<<<<<< HEAD
    "fastapi>=0.128.4",
    "pydantic[email]>=2.12.5",
    "python-jose[cryptography]>=3.5.0",
    "sqlalchemy>=2.0.46",
=======
    "dotenv>=0.9.9",
    "fastapi>=0.128.4",
    "fastapi-mail>=1.6.1",
    "pywhatkit>=5.4",
    "twilio>=9.10.1",
>>>>>>> origin/main
    "uvicorn>=0.40.0",
]
